python2_service = """
service1
service2
service3
"""

pipeline {
  agent any
  parameters {
        booleanParam(name: 'PYTHON2_DEPLOY', defaultValue: true, description: 'Branch to Deploy, paste the desired branch')
        text(
            defaultValue: python2_service,
            name: 'PYTHON2_SERVICES'
        )
    }
  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Print message') {
      steps {
        script {
            def test = params.PYTHON2_SERVICES.tokenize( '\n' )
            echo "Some message ${test}"
        }
      }
    }
  }
}